# SwiftLint configuration for MoleUI

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - line_length

# Opt-in rules
opt_in_rules:
  - empty_count
  - empty_string

# Excluded directories
excluded:
  - Pods
  - .build
  - DerivedData
  - docs

# Line length configuration
line_length:
  warning: 120
  error: 200

# Identifier naming configuration
identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
    error: 50

# File length configuration
file_length:
  warning: 500
  error: 1000

# Function length configuration
function_body_length:
  warning: 50
  error: 100

# Type body length configuration
type_body_length:
  warning: 300
  error: 500

# Custom rules
custom_rules:
  # os.log (Logger) 不接受运行时 String 拼接（+ 运算符）
  # 必须使用单个字符串字面量 + 插值，或先赋值为局部变量再插值
  # 错误示例: logger.info("foo" + bar)
  # 正确示例: logger.info("foo \(bar)")  或  let s = "foo" + bar; logger.info("\(s)")
  oslog_no_string_concat:
    name: "os.log String Concatenation"
    regex: 'logger\.(trace|debug|info|notice|warning|error|critical|fault)\s*\(\s*"[^"]*"\s*\+'
    message: "os.log methods do not accept runtime String concatenation (+). Use string interpolation within a single literal, or assign to a variable first."
    severity: error
