# SwiftLint configuration for MoleUI

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - line_length

# Opt-in rules
opt_in_rules:
  - empty_count
  - empty_string

# Excluded directories
excluded:
  - Pods
  - .build
  - DerivedData
  - docs

# Line length configuration
line_length:
  warning: 120
  error: 200

# Identifier naming configuration
identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
    error: 50

# File length configuration
file_length:
  warning: 500
  error: 1000

# Function length configuration
function_body_length:
  warning: 50
  error: 100

# Type body length configuration
type_body_length:
  warning: 300
  error: 500
